name: "Sync GHAS to Jira"

on:
  schedule:
    - cron: '*/10 * * * *'    # trigger synchronization every 10 minutes
  workflow_dispatch:
    

jobs:
  test_job:
    runs-on: ubuntu-latest
    steps:
      - name: Sync alerts to Jira issues
        uses: github/ghas-jira-integration@v1
        with:
          jira_url: 'https://devtoolsindia.atlassian.net/'
          jira_user: 'pramodhm@devtools.in'
          jira_token: '6WsmecwEFhC4y8XskEFU1106'
          jira_project: 'GAP'
          github_token: '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'
          sync_direction: 'gh2jira'
